<?php
// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!interface_exists('Demo_Printer'))
{
    interface Demo_Printer
    {
        public function printString($s);
    }

    class Demo_PrinterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::Demo::Printer', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Demo::Printer', $facet);
        }
    }

    $Demo__t_Printer = IcePHP_defineClass('::Demo::Printer', 'Demo_Printer', -1, true, false, $Ice__t_Object, null, null);

    $Demo__t_PrinterPrx = IcePHP_defineProxy($Demo__t_Printer);

    IcePHP_defineOperation($Demo__t_Printer, 'printString', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_string, false, 0), null);
}
?>
